config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('spaffnerds.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('spaffnerds.setlists.urls', namespace='setlists')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

spaffnerds/setlists/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'shows/$',
        view=views.ShowListView.as_view(),
        name='show-list'
    ),
    url(
        regex=r'shows/(?P<year>[0-9]{4})-(?P<month>[0-9]{2})-(?P<day>[0-9]{2})/$',
        view=views.ShowDayView.as_view(),
        name='show-day'
    ),
    url(
        regex=r'shows/(?P<year>[0-9]{4})-(?P<month>[0-9]{2})-(?P<day>[0-9]{2})/(?P<slug>[0-9]{1,2})$$',
        view=views.ShowDetailView.as_view(),
        name='show-detail'
    ),

    url(
        regex=r'songs/$',
        view=views.SongListView.as_view(),
        name='song-list'
    ),
    url(
        regex=r'songs/(?P<slug>[\w-]+)$',
        view=views.SongDetailView.as_view(),
        name='song-detail'
    ),

    url(
        regex=r'venues/$',
        view=views.VenueListView.as_view(),
        name='venue-list'
    ),
    url(
        regex=r'venues/(?P<slug>[\w-]+)$',
        view=views.VenueDetailView.as_view(),
        name='venue-detail'
    ),
]

spaffnerds/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

spaffnerds/setlists/models.py
from django.db import models
from django.core.urlresolvers import reverse

from autoslug import AutoSlugField

# Create your models here.

class Song(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title')
    is_cover = models.BooleanField(default=0)
    lyrics = models.TextField(blank=True)
    # written_by = models.ForeignKey(Artist.name)

    def __str__(self):
        return self.title


class Artist(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
#     group = models.ForeignKey(Group.name)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)


class Venue(models.Model):
    name = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='name')
    loc_city = models.CharField(max_length=100, blank=True)
    loc_state = models.CharField(max_length=5, blank=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    description = models.TextField(blank=True)
    is_closed = models.BooleanField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("venue-detail", kwargs={'slug': self.slug})


class Show(models.Model):
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    date = models.DateField()
    date_order = models.IntegerField(default=1)
    notes = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    songs = models.ManyToManyField(Song, through='ShowSongLink')

    def __str__(self):
        return str(self.date)

    def get_show_day(self):
        return reverse('setlists:show-day', kwargs = {
                        'year': self.date.strftime("%Y"),
                        'month': self.date.strftime("%m"),
                        'day': self.date.strftime("%d")})

    def get_absolute_show(self):
        return reverse('setlists:show-detail', kwargs = {
                        'year': self.date.strftime("%Y"),
                        'month': self.date.strftime("%m"),
                        'day': self.date.strftime("%d"),
                        'slug': self.date_order})


    class Meta:
        ordering = ('date', 'date_order')


class ShowSongLink(models.Model):
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)

    track_number = models.IntegerField()
    set = models.IntegerField(null=True, blank=True)  # (1,2,3,E1,E2)
    notes = models.TextField(blank=True)
    is_segued = models.BooleanField(default=0)
    # guest? link to artists

    def __str__(self):
        return "%s: %s - %s" % (self.show.date, self.track_number, self.song.title)

    class Meta:
        ordering = ('track_number',)

spaffnerds/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from spaffnerds.database import Column, Model, SurrogatePK, db, reference_col, relationship
from spaffnerds.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

spaffnerds/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

spaffnerds/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(Form):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True

spaffnerds/music/views.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user

from sqlalchemy.sql import func

from spaffnerds.extensions import login_manager
# from spaffnerds.music.forms import LoginForm
# from spaffnerds.user.forms import RegisterForm
# from spaffnerds.user.models import User
from spaffnerds.utils import flash_errors

from spaffnerds.music.models import Song
from spaffnerds.music.models import Venue
from spaffnerds.music.models import Show

import datetime

blueprint = Blueprint('music', __name__, static_folder='../static')


@blueprint.route('/')
def home():
    """ 
        Home page
    """
    # upcoming shows
    current_time = datetime.datetime.utcnow()
    upcoming_shows = Show.query.filter_by(Show.date >= current_time).order_by()
    return render_template('music/home.html')


@blueprint.route('/songs/')
def songs():
    """Register new user."""
    songs = Song.query.all()
    return render_template('music/songs.html', data=songs)


@blueprint.route('/songs/<name>')
def song(name):
    """Register new user."""
    name = name.lower().replace(' ', '-')
    song = Song.query.filter_by(system_name=name).first_or_404()
    # venues = song.venues

    # get date last played

    return render_template('music/song.html', data=song)


@blueprint.route('/venues/')
def venues():

    venues = Venue.query.order_by(Venue.name).all()

    # date first played
    # date last played
    # times played
    # stats = Venue.query(func.min(date))
    return render_template('music/venues.html', data=venues)


@blueprint.route('/venues/<name>')
def venue(name):
    """Register new user."""
    venue = Venue.query.filter_by(name=name).first_or_404()
    return render_template('music/venue.html', data=venue)


@blueprint.route('/shows/')
def shows():
    """Register new user."""
    shows = Show.query.order_by(Show.date.desc()).all()
    return render_template('music/shows.html', data=shows)


@blueprint.route('/shows/<date>', methods=['GET', 'POST'])
def show(date):
    """Register new user."""
    show = Show.query.filter_by(date=date).first_or_404()

    songs = {}
    notes = []
    for song in show.song_assoc:
        song_ = (song.track_order, song.song_name, song.song_sys_name, song.segued, bool(song.song_notes))
        if song.song_notes:
            notes.append(song.song_notes)
        sset = song.show_set.replace('E1', 'Encore')

        songs.setdefault(sset, []).append(song_)

    print songs
    return render_template('music/show.html', data=show, songs_data=songs,notes=notes)

spaffnerds/setlists/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.views.generic.dates import DayArchiveView, DateDetailView, ArchiveIndexView
from django.core.urlresolvers import reverse

from braces.views import LoginRequiredMixin

from .models import Show, Song, Venue
# Create your views here.


class ShowListView(ArchiveIndexView):
    model = Show
    date_field = "date"

    def get_queryset(self):
        queryset = super(ShowListView, self).get_queryset()
        #
        # q = self.request.GET.get("q")
        #
        # if q:
        #     return queryset.filter(slug=q)
        return queryset


class ShowDayView(DayArchiveView):
    model = Show
    date_field = 'date'
    year_format = '%Y'
    month_format = '%m'
    day_format = '%d'



class ShowDetailView(DateDetailView):
    model = Show
    date_field = 'date'
    slug_field = 'date_order'
    year_format = '%Y'
    month_format = '%m'
    day_format = '%d'
    template_name = 'setlists/show_detail.html'

class SongListView(ListView):
    model = Song

    def get_queryset(self):
        queryset = super(SongListView, self).get_queryset()
        #
        # q = self.request.GET.get("q")
        #
        # if q:
        #     return queryset.filter(slug=q)
        return queryset


class SongDetailView(DetailView):
    model = Song
    slug_field = 'slug'


class VenueListView(ListView):
    model = Venue

    def get_queryset(self):
        queryset = super(VenueListView, self).get_queryset()
        #
        # q = self.request.GET.get("q")
        #
        # if q:
        #     return queryset.filter(slug=q)
        return queryset


class VenueDetailView(DetailView):
    model = Venue
    slug_field = 'slug'

spaffnerds/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

spaffnerds/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

spaffnerds/templates/setlists/show_archive.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Shows{% endblock %}

{% block content %}
<div class="container">
  <h2>Shows</h2>

  <div class="list-group">
    {% for show in latest %}
{#      <a href="{% url 'setlists:show-detail' show.date|date:"Y-m-d" %}" class="list-group-item">#}
          <a href="{{ show.get_show_day }}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ show.date }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}

spaffnerds/templates/setlists/show_archive_day.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ show.date }}{% endblock %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-sm-12">
        <h1>{{ day }}</h1>
    </div>
</div>

  <div class="list-group">
    {% for show in show_list %}
      <a href="{{ show.get_absolute_show }}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ show.venue.name }}</h4>
      </a>

        <!-- Action buttons -->
        <div class="row">

          <div class="col-sm-12">
          </div>

        </div>
        <!-- End Action buttons -->
        <div class="row">
        </div>
    {% endfor %}

  </div>

{# Date navigation controls#}
<p>
    {% if previous_day %}
        Previous Day: {{ previous_day }}
    {% endif %}
    {% if previous_day and next_day %}--{% endif %}
    {% if next_day %}
        Next Day: {{ next_day }}
    {% endif %}
</p>
{# end date nav <controls></controls>#}
</div>
{% endblock content %}

spaffnerds/templates/setlists/show_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ show.date }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
          <h2>{{ show.date }}</h2>
            <p>{{ show.venue.name }}</p>
        </div>
    </div>

    <!-- Action buttons -->
    <div class="row">

      <div class="col-sm-12">
      </div>

    </div>
    <!-- End Action buttons -->
    <div class="row">

      <div class="col-sm-12">
          {% if show.notes %}
            <p>{{ show.notes }}</p>
          {% endif %}
      </div>

    </div>

{# Date navigation controls#}
<p>
    {% if previous_day %}
        Previous Day: {{ previous_day }}
    {% endif %}
    {% if previous_day and next_day %}--{% endif %}
    {% if next_day %}
        Next Day: {{ next_day }}
    {% endif %}
</p>
{# end date nav <controls></controls>#}
</div>
{% endblock content %}

spaffnerds/templates/setlists/show_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Shows</h2>

  <div class="list-group">
    {% for show in show_list %}
      <a href="{% url 'setlists:show-detail' show.date %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ show.date }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}

spaffnerds/templates/setlists/song_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ song.title }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ song.title }}</h2>
    </div>
  </div>

<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
  </div>

</div>
<!-- End Action buttons -->

<!-- Lyrics -->
{% if song.lyrics %}
<div class="row">
    <div class="col-sm-12">
        <div class="card card-block bg-faded">
            <h4 class="card-title">Lyrics</h4>
            <p class="card-text">{{ song.lyrics|linebreaks }}</p>
        </div>
    </div>
</div>
{% endif %}
<!-- End Lyrics -->

</div>
{% endblock content %}

spaffnerds/templates/setlists/song_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Songs</h2>

  <div class="list-group">
    {% for song in song_list %}
      <a href="{% url 'setlists:song-detail' song.slug %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ song.title }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}

spaffnerds/templates/setlists/venue_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ venue.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ venue.name }}</h2>
    </div>
  </div>

<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
  </div>

</div>
<!-- End Action buttons -->
<div class="row">

  <div class="col-sm-12">
      {% if venue.description %}
        <p>{{ venue.description }}</p>
      {% endif %}
  </div>

</div>

</div>
{% endblock content %}

spaffnerds/templates/setlists/venue_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Venues{% endblock %}

{% block content %}
<div class="container">
  <h2>Venues</h2>

  <div class="list-group">
    {% for venue in venue_list %}
      <a href="{% url 'setlists:venue-detail' slug=venue.slug %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ venue.name }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}