config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('spaffnerds.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('spaffnerds.setlists.urls', namespace='setlists')),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

spaffnerds/setlists/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'shows/$',
        view=views.ShowListView.as_view(),
        name='show-list'
    ),
    url(
        regex=r'shows/(?P<year>[0-9]{4})-(?P<month>[0-9]{2})-(?P<day>[0-9]{2})/$',
        view=views.ShowDayView.as_view(),
        name='show-day'
    ),
    url(
        regex=r'shows/(?P<year>[0-9]{4})-(?P<month>[0-9]{2})-(?P<day>[0-9]{2})/(?P<slug>[0-9]{1,2})$$',
        view=views.ShowDetailView.as_view(),
        name='show-detail'
    ),

    url(
        regex=r'songs/$',
        view=views.SongListView.as_view(),
        name='song-list'
    ),
    url(
        regex=r'songs/(?P<slug>[\w-]+)$',
        view=views.SongDetailView.as_view(),
        name='song-detail'
    ),

    url(
        regex=r'venues/$',
        view=views.VenueListView.as_view(),
        name='venue-list'
    ),
    url(
        regex=r'venues/(?P<slug>[\w-]+)$',
        view=views.VenueDetailView.as_view(),
        name='venue-detail'
    ),
]

spaffnerds/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

spaffnerds/setlists/models.py
from django.db import models
from django.core.urlresolvers import reverse

from autoslug import AutoSlugField

# Create your models here.

class Song(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title')
    is_cover = models.BooleanField(default=0)
    lyrics = models.TextField(blank=True)
    # written_by = models.ForeignKey(Artist.name)

    def __str__(self):
        return self.title


class Artist(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
#     group = models.ForeignKey(Group.name)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)


class Venue(models.Model):
    name = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='name')
    loc_city = models.CharField(max_length=100, blank=True)
    loc_state = models.CharField(max_length=5, blank=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    description = models.TextField(blank=True)
    is_closed = models.BooleanField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("venue-detail", kwargs={'slug': self.slug})


class Show(models.Model):
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    date = models.DateField()
    date_order = models.IntegerField(default=1)
    notes = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    songs = models.ManyToManyField(Song, through='ShowSongLink')

    def __str__(self):
        return str(self.date)

    def get_show_day(self):
        return reverse('setlists:show-day', kwargs = {
                        'year': self.date.strftime("%Y"),
                        'month': self.date.strftime("%m"),
                        'day': self.date.strftime("%d")})

    def get_absolute_show(self):
        return reverse('setlists:show-detail', kwargs = {
                        'year': self.date.strftime("%Y"),
                        'month': self.date.strftime("%m"),
                        'day': self.date.strftime("%d"),
                        'slug': self.date_order})


    class Meta:
        ordering = ('date', 'date_order')


class ShowSongLink(models.Model):
    show = models.ForeignKey(Show, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)

    track_number = models.IntegerField()
    set = models.IntegerField(null=True, blank=True)  # (1,2,3,E1,E2)
    notes = models.TextField(blank=True)
    is_segued = models.BooleanField(default=0)
    # guest? link to artists

    def __str__(self):
        return "%s: %s - %s" % (self.show.date, self.track_number, self.song.title)

    class Meta:
        ordering = ('track_number',)

spaffnerds/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from spaffnerds.database import Column, Model, SurrogatePK, db, reference_col, relationship
from spaffnerds.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

spaffnerds/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

spaffnerds/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(Form):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True

spaffnerds/music/views.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user

from sqlalchemy.sql import func

from spaffnerds.extensions import login_manager
# from spaffnerds.music.forms import LoginForm
# from spaffnerds.user.forms import RegisterForm
# from spaffnerds.user.models import User
from spaffnerds.utils import flash_errors

from spaffnerds.music.models import Song
from spaffnerds.music.models import Venue
from spaffnerds.music.models import Show

import datetime

blueprint = Blueprint('music', __name__, static_folder='../static')


@blueprint.route('/')
def home():
    """ 
        Home page
    """
    # upcoming shows
    current_time = datetime.datetime.utcnow()
    upcoming_shows = Show.query.filter_by(Show.date >= current_time).order_by()
    return render_template('music/home.html')


@blueprint.route('/songs/')
def songs():
    """Register new user."""
    songs = Song.query.all()
    return render_template('music/songs.html', data=songs)


@blueprint.route('/songs/<name>')
def song(name):
    """Register new user."""
    name = name.lower().replace(' ', '-')
    song = Song.query.filter_by(system_name=name).first_or_404()
    # venues = song.venues

    # get date last played

    return render_template('music/song.html', data=song)


@blueprint.route('/venues/')
def venues():

    venues = Venue.query.order_by(Venue.name).all()

    # date first played
    # date last played
    # times played
    # stats = Venue.query(func.min(date))
    return render_template('music/venues.html', data=venues)


@blueprint.route('/venues/<name>')
def venue(name):
    """Register new user."""
    venue = Venue.query.filter_by(name=name).first_or_404()
    return render_template('music/venue.html', data=venue)


@blueprint.route('/shows/')
def shows():
    """Register new user."""
    shows = Show.query.order_by(Show.date.desc()).all()
    return render_template('music/shows.html', data=shows)


@blueprint.route('/shows/<date>', methods=['GET', 'POST'])
def show(date):
    """Register new user."""
    show = Show.query.filter_by(date=date).first_or_404()

    songs = {}
    notes = []
    for song in show.song_assoc:
        song_ = (song.track_order, song.song_name, song.song_sys_name, song.segued, bool(song.song_notes))
        if song.song_notes:
            notes.append(song.song_notes)
        sset = song.show_set.replace('E1', 'Encore')

        songs.setdefault(sset, []).append(song_)

    print songs
    return render_template('music/show.html', data=show, songs_data=songs,notes=notes)

spaffnerds/setlists/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.views.generic.dates import DayArchiveView, DateDetailView, ArchiveIndexView
from django.core.urlresolvers import reverse

from braces.views import LoginRequiredMixin

from .models import Show, Song, Venue
# Create your views here.


class ShowListView(ArchiveIndexView):
    model = Show
    date_field = "date"

    def get_queryset(self):
        queryset = super(ShowListView, self).get_queryset()
        #
        # q = self.request.GET.get("q")
        #
        # if q:
        #     return queryset.filter(slug=q)
        return queryset


class ShowDayView(DayArchiveView):
    model = Show
    date_field = 'date'
    year_format = '%Y'
    month_format = '%m'
    day_format = '%d'



class ShowDetailView(DateDetailView):
    model = Show
    date_field = 'date'
    slug_field = 'date_order'
    year_format = '%Y'
    month_format = '%m'
    day_format = '%d'
    template_name = 'setlists/show_detail.html'

class SongListView(ListView):
    model = Song

    def get_queryset(self):
        queryset = super(SongListView, self).get_queryset()
        #
        # q = self.request.GET.get("q")
        #
        # if q:
        #     return queryset.filter(slug=q)
        return queryset


class SongDetailView(DetailView):
    model = Song
    slug_field = 'slug'


class VenueListView(ListView):
    model = Venue

    def get_queryset(self):
        queryset = super(VenueListView, self).get_queryset()
        #
        # q = self.request.GET.get("q")
        #
        # if q:
        #     return queryset.filter(slug=q)
        return queryset


class VenueDetailView(DetailView):
    model = Venue
    slug_field = 'slug'

spaffnerds/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

spaffnerds/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

spaffnerds/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

spaffnerds/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

spaffnerds/templates/base.html
    {% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Spaffnerds{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">Spaffnerds</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'setlists:show-list' %}">Shows</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'setlists:song-list' %}">Songs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'setlists:venue-list' %}">Venues</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

spaffnerds/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Evan Locke</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:evan.locke@gmail.com">Contact</a></li>
    </ul>
  </small>
</footer>

spaffnerds/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    Spaffnerds
  
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

spaffnerds/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">

      Spaffnerds

    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
      <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Music <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{ url_for('music.venues') }}">Venues</a></li>
          <li><a href="{{ url_for('music.shows') }}">Shows</a></li>
          <li><a href="{{ url_for('music.songs') }}">Songs</a></li>
        </ul>
      </li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

    </ul>
    {% elif form %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.register') }}">Create account</a></li>
    </ul>
    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username(placeholder="Username", class_="form-control") }}
        {{ form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button type="submit" class="btn btn-default">Log in</button>
    </form>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>